changelog:
  categories:
  - title: New Features
    labels:
    - enhancement
  - title: Documentation Changes
    labels:
    - documentation
  - title: Example
    labels:
    - example
  - title: Bug Fixes
    labels:
    - bug
  - title: Deprecations
    labels:
    - deprecated
  - title: Dependency Updates
    labels:
    - dependencies
  - title: Other Changes
    labels:
       - "*"
